<div id="footer">
	<div class="inner">
		<div class="primary">
			<p class="first">Copyright (c) 2013 <a href="http://www.veboolabs.com">上海复佳办公设备有限公司</a> </p>
			<p>上海市天山西路125号B座530室 沪ICP备13044122号-1</p>
		</div>
		<div class="secondary">
			<p class="first">我们是一家绿色的公司</p>
			<p>我们关心着环境，努力让身边充满更多绿色</p>
		</div>
	</div>
</div>

    <div style="display:none">
      <script type="text/javascript">
      var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
      document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F0ec40fc5671a0e10cf3e7d553db7807f' type='text/javascript'%3E%3C/script%3E"));
      </script>
    </div>


</body>


</html>
