
    </div> <!-- /container -->
    
    <style>
    	footer {
    		margin-top:50px;
    		padding-top:30px;
    		padding-bottom:30px;
    		position: relative;
  			text-align: center;
  			background-color: #555555;
  			width:100%;
  		}
    </style>

    <footer>
      <p>Copyright 2012 上海复佳办公设备有限公司 沪ICP备12000979号 </p>
    </footer>

    <div style="display:none">
      <script type="text/javascript">
      var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
      document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F0ec40fc5671a0e10cf3e7d553db7807f' type='text/javascript'%3E%3C/script%3E"));
      </script>
    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery-1.8.1.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.masonry.min.js"></script>
  
		<script>
			$(function(){
				$('.carousel').carousel();
			});
		</script>

  </body>

</html>
